# Generated by Django 6.0.3 on 2026-03-17 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_captionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('platforms', models.JSONField(default=list)),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.batchprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.workspace')),
            ],
        ),
    ]
