# Generated by Django 6.0.3 on 2026-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hashtag_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
