# Generated by Django 6.0.3 on 2026-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaign_hashtag_count_campaign_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionhistory',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
