# Generated by Django 6.0.3 on 2026-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_captionhistory_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprofile',
            name='hashtag_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchprofile',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='batchprofile',
            name='length',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
