# Generated by Django 6.0.3 on 2026-03-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_captionhistory_platforms_captionhistory_results_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='captionhistory',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='captionhistory',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='captionhistory',
            name='platform',
        ),
    ]
