# Generated by Django 6.0.3 on 2026-03-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_systemconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='gemini_api_key',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='gemini_api_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
